# -*- coding: utf-8 -*-
"""DL01_2Ada

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L-ygMVNlLLPAYqS0JoZAMepBgfbLGqZG
"""

import numpy as np
import matplotlib.pyplot as plt

x_data=[-10,-8,-5,-2,0,1,4,6,8,12]
y_data=np.zeros(10)
for i in range(len(x_data)):
  y_data[i]=2*x_data[i]+1
#y_data=w*x_data+b  , w=2, b=1

x_axis=np.arange(-5,5,0.1)#bias
y_axis=np.arange(-5,5,0.1)#weight
Z=np.zeros( (len(x_axis),len(y_axis))  )
X,Y = np.meshgrid(x_axis,y_axis)

for i in range(len(x_axis)):
	for j in range(len(y_axis)):
		b=x_axis[i]
		w=y_axis[j]
		Z[j][i]=0
		for n in range(len(x_data)):
			y_hat=w*x_data[n]+b
			Z[j][i]=Z[j][i]+(y_data[n]-y_hat)**2
		Z[j][i]=Z[j][i]/len(x_data)

plt.contourf(X,Y,Z,50,alpha=0.5,cmap=plt.get_cmap('jet'))
plt.xlabel(r'$b$',fontsize=16)
plt.ylabel(r'$w$',fontsize=16)

#ydata=b+w*xdata
w = -4	# initial w
b = -4  # initial b
lr=1
iteration=50

b_history=[b]
w_history=[w]

lr_b = 0  #
lr_w = 0  #

for i in range(iteration):
	b_grad=0.0
	w_grad=0.0
	for n in range(len(x_data)):
		b_grad=b_grad -2.0*(y_data[n]-b-w*x_data[n])*1.0
		w_grad=w_grad -2.0*(y_data[n]-b-w*x_data[n])*x_data[n]
	
	lr_b = lr_b + b_grad**2
	lr_w = lr_w + w_grad**2

	b=b-lr/np.sqrt(lr_b)*b_grad
	w=w-lr/np.sqrt(lr_w)*w_grad

	b_history.append(b)
	w_history.append(w)
 
plt.contourf(X,Y,Z,50,alpha=0.5,cmap=plt.get_cmap('jet'))
plt.plot([1],[2],'x',ms=12,markeredgewidth=3,color='orange')
plt.plot(b_history,w_history,'o-',ms=3,lw=1.5,color='black')
plt.xlim(-5,5)
plt.ylim(-5,5)
plt.xlabel(r'$b$',fontsize=16)
plt.ylabel(r'$w$',fontsize=16)
plt.show()