# -*- coding: utf-8 -*-
"""DL02b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJ-eC3KzTGfZawS8_7gtYu0524tJt9zh
"""

from tensorflow import keras
model = keras.models.load_model('drive/MyDrive/00AI/mnist_model')

model.summary()

#from tensorflow.keras.datasets import mnist
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

import matplotlib.pyplot as plt
image=test_images[370]
plt.imshow(image,cmap='gray')
#plt.imshow(image)

image.shape

x=test_images[370].reshape(1,784)
x.shape

x=x/255.0
prediction = model.predict(x)
print(prediction)

import numpy as np
np.argmax(prediction)

alphabet = "0123456789"
dictionary = {}
for i in range(10):
	dictionary[i] = alphabet[i]
dictionary

dictionary[np.argmax(prediction)]

#from tensorflow.keras.preprocessing import image as image_utils
image_utils=tf.keras.preprocessing.image
def load_and_scale_image(image_path):
    image = image_utils.load_img(image_path, color_mode="grayscale", target_size=(28,28))
    return image

image = load_and_scale_image('drive/MyDrive/00AI/04.bmp')
plt.imshow(image,cmap='gray')

image.size

image = image_utils.img_to_array(image)
image.shape

image = image.reshape(28,28)
x=image.reshape(1,784)
x.shape

x=x/255.0
prediction = model.predict(x)
print(prediction)
np.argmax(prediction)

image = load_and_scale_image('drive/MyDrive/00AI/05.jpg')
plt.imshow(image,cmap='gray')
image = image_utils.img_to_array(image)
image = image.reshape(28,28)
x=image.reshape(1,784)
x=x/255.0
prediction = model.predict(x)
print(prediction)
np.argmax(prediction)

image = load_and_scale_image('drive/MyDrive/00AI/02.png')
plt.imshow(image,cmap='gray')
image = image_utils.img_to_array(image)
image = image.reshape(28,28)
x=image.reshape(1,784)
x=x/255.0
prediction = model.predict(x)
print(prediction)
np.argmax(prediction)

import matplotlib.image as mpimg
def show_image(image_path):
  image = mpimg.imread(image_path)
  #plt.imshow(image,cmap='gray')
  plt.imshow(image)

show_image('drive/MyDrive/00AI/05.jpg')