# -*- coding: utf-8 -*-
"""DL03b.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z-5YdH430Q7Dstz5L6Zl5VDixFtzfW9_
"""

import pandas as pd

train_df = pd.read_csv("drive/MyDrive/00AI/sign_mnist_train.csv")
valid_df = pd.read_csv("drive/MyDrive/00AI/sign_mnist_test.csv")

train_label = train_df['label']
valid_label = valid_df['label']
del train_df['label']
del valid_df['label']

# Separate out our image vectors
train_image = train_df.values
valid_image = valid_df.values

train_image = train_image / 255
valid_image = valid_image / 255

#import tensorflow.keras as keras
import tensorflow as tf
keras=tf.keras

num_classes = 25
train_label = keras.utils.to_categorical(train_label, num_classes)
valid_label = keras.utils.to_categorical(valid_label, num_classes)

train_image = train_image.reshape(-1,28,28,1) #灰階=1 RGB=3
valid_image = valid_image.reshape(-1,28,28,1)

train_image.shape, valid_image.shape

import tensorflow as tf
model=tf.keras.models.Sequential()
layers=tf.keras.layers
model.add(layers.Conv2D(75, (3, 3), strides=1, padding="same", activation="relu",input_shape=(28, 28, 1)))#padding=same旁邊填入相同數值
model.add(layers.BatchNormalization())
model.add(layers.MaxPool2D((2, 2), strides=2, padding="same"))
model.add(layers.Conv2D(50, (3, 3), strides=1, padding="same", activation="relu"))
model.add(layers.Dropout(0.2))
model.add(layers.BatchNormalization())
model.add(layers.MaxPool2D((2, 2), strides=2, padding="same"))
model.add(layers.Conv2D(25, (3, 3), strides=1, padding="same", activation="relu"))
model.add(layers.BatchNormalization())
model.add(layers.MaxPool2D((2, 2), strides=2, padding="same"))
model.add(layers.Flatten())
model.add(layers.Dense(units=512, activation="relu"))
model.add(layers.Dropout(0.3))
model.add(layers.Dense(units=num_classes, activation="softmax"))

model.summary()

model.compile(loss="categorical_crossentropy", metrics=["accuracy"])

model.fit(train_image, train_label, epochs=20, verbose=1, validation_data=(valid_image, valid_label))